#!/usr/bin/env python

import sys
import MySQLdb

db=MySQLdb.connect (user="wetnet",
                    passwd="wetnet123",
                    db="wetnet")

def usage(argv):
 if len(argv) == 1:
  print 'Usage: wetnet [create|query] [organization|supernet|set|subnet|host] [orgname|x.x.x.x/x] [device] device-id'
  sys.exit(0)

usage(sys.argv)
sys.argv.pop(0)
cmd=str(sys.argv[0])

def create_organization():
 print "create_organization"

def create_supernet():
 print "create_supernet"

def create_set():
 print "create_set"

def create_subnet():
 print "create_subnet"

def create_host():
 print "create_host"

def query_organization():
 print "query_organization"

def query_supernet():
 print "query_supernet"
 cursor = db.cursor ()
 cursor.execute ("SELECT VERSION()")
 row = cursor.fetchone ()
 print "server version:", row[0]
 cursor.close ()

def query_set():
 print "query_set"

def query_subnet():
 print "query_subnet"

def query_host():
 print "query_host"

def query():
 usage(sys.argv) 
 sys.argv.pop(0)
 print "you are querying " + sys.argv[0]
 options = {"organization" : query_organization,
            "supernet" : query_supernet,
            "set" : query_set,
            "subnet" : query_subnet,
            "host" : query_host
 }
 options[sys.argv[0]]()

def create():
 usage(sys.argv) 
 sys.argv.pop(0)
 print "you are creating"
 options = {"organization" : create_organization,
            "supernet" : create_supernet,
            "set" : create_set,
            "subnet" : create_subnet,
            "host" : create_host
 }
 options[sys.argv[0]]()

options = {"query" : query,
           "create" : create
}
options[cmd]()

