#!/usr/bin/env python

import sys

def usage(argv):
 if len(argv) == 1:
  print 'Usage: wetnet [create|query] [supernet|set|subnet|host] x.x.x.x/x [device] device-id'
  sys.exit(0)

usage(sys.argv)
sys.argv.pop(0)
cmd=str(sys.argv[0])

def query_supernet():
 print "query_supernet"

def query_set():
 print "query_set"

def query_subnet():
 print "query_subnet"

def query_host():
 print "query_host"

def query():
 usage(sys.argv) 
 sys.argv.pop(0)
 print "you are querying " + sys.argv[0]
 options = {"supernet" : query_supernet,
            "set" : query_set,
            "subnet" : query_subnet,
            "host" : query_host
 }
 options[sys.argv[0]]()

def create():
 print "you are creating"

options = {"query" : query,
           "create" : create
}
options[cmd]()

